Build Notification - BeetekShoeMonitor

Version: v1.0.0
Timestamp: 2025-11-28 18:00:00
Status: SUCCESS

Download Links:

macOS Intel: https://s3.ap-south-1.amazonaws.com/only-unity-build/shoe-monitor-builds/v1.0.0/macos-intel/BeetekShoeMonitor-macOS-Intel.zip

macOS Apple Silicon: https://s3.ap-south-1.amazonaws.com/only-unity-build/shoe-monitor-builds/v1.0.0/macos-arm/BeetekShoeMonitor-macOS-AppleSilicon.zip

Linux Ubuntu 22.04: https://s3.ap-south-1.amazonaws.com/only-unity-build/shoe-monitor-builds/v1.0.0/linux-ubuntu22/BeetekShoeMonitor-ubuntu22.04

Linux Ubuntu 24.04: https://s3.ap-south-1.amazonaws.com/only-unity-build/shoe-monitor-builds/v1.0.0/linux-ubuntu24/BeetekShoeMonitor-ubuntu24.04

Windows: https://s3.ap-south-1.amazonaws.com/only-unity-build/shoe-monitor-builds/v1.0.0/windows/BeetekShoeMonitor-Windows.zip

---
Wildace Automated Build System
